### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by h531497850** [zerodha/python-wheels#1]
λ python --version
Python 3.6.4

λ pip install C:\Users\Administrator\Desktop\Twisted-18.7.0-cp36-cp36m-win_amd64.whl
Twisted-18.7.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

**Comment by vividvilla** [comment]
From Pykiteconnect version 3.9.0 onwards you don't need this dep. For more details - https://github.com/zerodha/python-wheels/issues/4
